name: Basic Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Say Goodbye
        run: echo "Goodbye, World!"
  success:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Say Success
        run: echo "Build succeeded!"